import styles from "./Portfolio.module.css";
import SpotlightCard from "@/components/ui/SpotlightCard";
import ScrollReveal from "@/components/ui/ScrollReveal";

export default function Portfolio() {
  const items = [
    { name: "Acme Legal", category: "Corporate & Law", style: "Clean & Corporate", time: "42 Hours" },
    { name: "Nova SaaS", category: "B2B Software", style: "Modern & Professional", time: "38 Hours" },
    { name: "Studio XYZ", category: "Creative Agency", style: "Bold & Brutalist", time: "45 Hours" },
    { name: "Luxe Interiors", category: "High-end Real Estate", style: "Luxury & Minimal", time: "41 Hours" },
  ];

  return (
    <section id="portfolio" className={styles.portfolio}>
      <ScrollReveal className={styles.container}>
        <div className={styles.headerGroup}>
          <h2 className={styles.title}>Recent Manifestations</h2>
          <p className={styles.subtitle}>A glimpse into the digital architectures generated by our AI engine.</p>
        </div>
        <div className={styles.grid}>
          {items.map((item) => (
            <SpotlightCard key={item.name} className={styles.cardWrapper}>
              <div className={styles.placeholder}>
                <div className={styles.placeholderLogo}>{item.name.charAt(0)}</div>
                <span>{item.name}</span>
              </div>
              <div className={styles.info}>
                <div className={styles.infoHeader}>
                  <h3>{item.name}</h3>
                  <span className={styles.timeBadge}>{item.time}</span>
                </div>
                <p>{item.category} • {item.style}</p>
              </div>
            </SpotlightCard>
          ))}
        </div>
      </ScrollReveal>
    </section>
  );
}
